config/routes.rb
Rails.application.routes.draw do
  resources :tv_shows
  get '/tv_shows', to: 'tv_shows#index'
  get '/welcome', to: 'pages#welcome'
  root 'pages#welcome'
  post '/tv_shows', to: 'tv_shows#create'

  resources :tv_shows do
    member do
      get 'about'
    end
  end

  resources :tv_shows do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: %i[ show edit update destroy ]

  # GET /tv_shows or /tv_shows.json
  def index
    @tv_shows = TvShow.all
  end

  # GET /tv_shows/1 or /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows or /tv_shows.json
  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to tv_show_url(@tv_show), notice: "La Serie se ha creado satisfactoriamente." }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1 or /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to tv_show_url(@tv_show), notice: "La Serie ha sido actualizada correctamente." }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1 or /tv_shows/1.json
  def destroy
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: "La Serie fue eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  def search
    @search = TvShow.where('name LIKE %?%', params[:query])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tv_show_params
      params.require(:tv_show).permit(:name, :summary, :release_date, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavoriteTvSeries</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="display-4 text-success">My Favorite TV series</h1>
            <p class="lead text-secondary">Welcome!!!</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <div class="media">
                <%= image_tag('iron-man.jpg', size: "64x64", alt: "Iron Man", class: 'mr-3')%>
                <div class="media-body">
                    <h5 class="mt-0">Iron Man</h5>
                    2008's Iron Man tells the story of Tony Stark, a billionaire industrialist and genius inventor who is kidnapped and forced to build a devastating weapon. Instead, using his intelligence and ingenuity, Tony builds a high-tech suit of armor and escapes captivity.
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<%= link_to 'go back to welcome page', tv_shows_path %>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
        <% tv_show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre  %>
    <%= form.text_field :name , class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :detalle %>
    <%= form.text_area :summary , class: "form-control" %>
  </div>
<br>
  <div class="field">
    <%= form.label :fecha_de_lanzamiento %>
    <%= form.datetime_select :release_date  %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating , class: "form-control" %>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Agregar Serie" %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1 class="display-3">Editar Serie</h1>
<hr>
<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Ver', @tv_show %> |
<%= link_to 'Atrás', tv_shows_path %>

app/views/tv_shows/index.html.erb
<h1 class="display-3">Series</h1>
<hr>
<p id="notice"><%= notice %></p>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Detalle</th>
      <th>Fecha de lanzamiento</th>
      <th>Rating</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @tv_shows.each do |tv_show| %>
      <tr>
        <td><%= tv_show.name %></td>
        <td><%= tv_show.summary %></td>
        <td><%= tv_show.release_date %></td>
        <td><%= tv_show.rating %></td>
        <td><%= link_to 'Ver', tv_show , class: "btn btn-outline-secondary" %></td>
        <td><%= link_to 'Editar', edit_tv_show_path(tv_show) , class: "btn btn-outline-warning" %></td>
        <td><%= link_to 'Eliminar', tv_show, method: :delete, data: { confirm: 'Estás segur@?' } , class: "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar nueva serie', new_tv_show_path %>

app/views/tv_shows/new.html.erb
<h1 class="display-3">Agregar nueva serie</h1>
<hr>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Atrás', tv_shows_path %>

app/views/tv_shows/search.html.erb
<h1 class="display-3">Búsqueda</h1>
<hr>
<%= form_with url: "search", method: :get do |form| %>
    <%= form.label :query, "Buscar película o serie:" %>
    <%= form.text_field :query %>
    <%= form.submit "Buscar" %>
<% end %>

<%= "***Ningun dato encontrado***" unless @search %>

<p>
    <strong>Nombre:</strong>
    <%= @search.name %>
</p>

<p>
    <strong>Detalle:</strong>
    <%= @search.summary %>
</p>

<p>
    <strong>Fecha de lanzamiento:</strong>
    <%= @search.release_date %>
</p>

<p>
    <strong>Rating:</strong>
    <%= @search.rating %>
</p>

<%= link_to 'Atrás', tv_shows_path %>

app/views/tv_shows/show.html.erb
<h1 class="display-3">Estás viendo <%= @tv_show.name %></h1>
<hr>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tv_show.name %>
</p>

<p>
  <strong>Detalle:</strong>
  <%= @tv_show.summary %>
</p>

<p>
  <strong>Fecha de lanzamiento:</strong>
  <%= @tv_show.release_date %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @tv_show.rating %>
</p>

<%= link_to 'Editar', edit_tv_show_path(@tv_show) %> |
<%= link_to 'Atrás', tv_shows_path %>